#!/usr/bin/env bash

./ignore_binary_files.sh
list=`ls ./*`
for i in $list; do n=$(grep -oE "^|\.[a-z]{1,5}$" <<< $i) && bn=$(basename -s "$n" $i) && git add $i && git commit -m "submit $bn" && git push && sleep 12;done
